version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - memcache
  bot:
    build: ./bot
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
  memcache:
    image: memcached:latest
    ports:
      - "11211:11211"
